language: php

php:
  - 5.4
  - 5.5

addons:
  hosts:
    - cuisine.dev
  code_climate:
    repo_token: 222f6b907fed2dce854442dde1f73ad32ee748766f96f80c3f3ee9250bb05e8b


before_script:
  - mkdir tests/_log
  - mkdir app/storage/logs
  - chmod 777 -R tests/_log
  - chmod 777 -R app/storage
  - touch .travis_env
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database db_test;'
  - php artisan env
  - travis_retry php artisan migrate --force --seed

script: php artisan qa:test --coverage=xml

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/_log/coverage.xml