language: php

php:
  - 5.4

addons:
  hosts:
    - cuisine.dev

before_script:
  - mkdir tests/_log
  - chmod 777 -R tests/_log
  - chmod 777 -R app/storage
  - touch .travis_env
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database db_test;'
  - php artisan env
  - travis_retry php artisan migrate --force --seed
  - php artisan serve --host=cuisine.dev --port=80
  - sleep 10

script: vendor/bin/codecept run