language: php

php:
  - 5.4

before_script:
  - mkdir tests/_log
  - chmod 777 -R tests/_log
  - chmod 777 -R app/storage
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mysql -e 'create database db_test;'
  - travis_retry php artisan migrate
  - travis_retry php artisan db:seed

script: vendor/bin/codecept run